User.create!(email: "admin@domain.com", password: "password", password_confirmation: "password")
Supplement.create!(name: "John Lennon", amount: 10)
Supplement.create!(name: "Paul McCartney", amount: 120)
Supplement.create!(name: "Georges Harrison", amount: 90)
Supplement.create!(name: "Ringo Starr", amount: 60)
Supplement.create!(name: "Mick Jagger", amount: 90)
Supplement.create!(name: "Keith Richards", amount: 100)
Supplement.create!(name: "Mick Taylor", amount: 120)
Supplement.create!(name: "Bill Wyman", amount: 60)
Supplement.create!(name: "Charlie Watts", amount: 300)
Supplement.create!(name: "Angus Young", amount: 25)
Supplement.create!(name: "Malcom Young", amount: 45)
Supplement.create!(name: "Bon Scott", amount: 10)
Supplement.create!(name: "Phil Rudd", amount: 250)
